version: "3.3"
services:
  discord_client:
    build: apps/discord_client
    volumes:
      - ./data:/data
    restart: always
    depends_on:
      - server
  telegram_client:
    build: apps/telegram_client
    volumes:
      - ./data:/data
    restart: always
    depends_on:
      - server
  docker_proxy:
    build: apps/docker_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  compiler_server:
    build: apps/compiler_server
    privileged: true
    restart: always
  server:
    build: apps/server
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    restart: always
