version: "3.9"
services:
  discord_client:
    build: apps/discord_client
    volumes:
      - ./data:/data
    restart: always
  whatsapp_client:
    build: apps/whatsapp_client
    volumes:
      - ./data:/data
    restart: always
  docker_proxy:
    build: apps/docker_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3565:3565"
    restart: always
  compiler_server:
    build: apps/compiler_server
    ports:
      - "3566:3566"
    privileged: true
    restart: always
  server:
    build: apps/server
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    restart: always